### ISSUE TITLE
thanks for your code. I learn a lot from it.

### ISSUE THREAD

**Issue by kjfjsd99** [VladimirSinitsin/person_reid_yolo#2]

**Comment by VladimirSinitsin** [comment]
Hi! Thank you so much for paying attention to my repository. I got an email notification with the full issue, so I'll show you where the `mark_frame` function is "lost" :)

In the `run.py` file, it is imported from the `tools` package
https://github.com/VladimirSinitsin/person_reid_yolo/blob/a3f8f57a886cc388e3098c6de3a91deb25e2e03c/run.py#L10

Then in the `__init__.py` file of the `tools` package, it is configured to import it from the `frame_marker.py` file. This is done to import it simply as `from tools import mark_frame` rather than `from tools.frame_marker import mark_frame` :)
https://github.com/VladimirSinitsin/person_reid_yolo/blob/a3f8f57a886cc388e3098c6de3a91deb25e2e03c/tools/__init__.py#L2

And already in `frame_marker.py` you can find this function
https://github.com/VladimirSinitsin/person_reid_yolo/blob/a3f8f57a886cc388e3098c6de3a91deb25e2e03c/tools/frame_marker.py#L23

Good luck in your learning!
